name: Deploy Python Shiny App to shinyapps.io

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rsconnect-python
          pip install -r requirements.txt

      - name: Setup Env variables
        env:
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
          SHINY_ACCOUNT: ${{ secrets.SHINY_ACCOUNT }}
          SHINY_APP_ID: ${{ secrets.SHINY_APP_ID }}
          SHINY_APP_NAME: ${{ secrets.SHINY_APP_NAME}}
        run: |
          echo "variable setup" 

      - name: Deploy to shinyapps.io with known app name
        env:
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
          SHINY_ACCOUNT: ${{ secrets.SHINY_ACCOUNT }}
          SHINY_APP_ID: ${{ secrets.SHINY_APP_ID }}
          SHINY_APP_NAME: ${{ secrets.SHINY_APP_NAME}}
        run: |
          rsconnect deploy shiny ./ \
          --account $SHINY_ACCOUNT \
          --server shinyapps.io \
          --token $SHINY_TOKEN \
          --secret $SHINY_SECRET \
          --title $SHINY_APP_NAME \
          -a $SHINY_APP_ID \
        if: env.SHINY_APP_ID != ''
        
      - name: Deploy to shinyapps.io with NEW app name
        env:
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
          SHINY_ACCOUNT: ${{ secrets.SHINY_ACCOUNT }}
          SHINY_APP_ID: ${{ secrets.SHINY_APP_ID }}
          SHINY_APP_NAME: ${{ secrets.SHINY_APP_NAME}}
        run: |
          rsconnect deploy shiny ./ \
          --account $SHINY_ACCOUNT \
          --server shinyapps.io \
          --token $SHINY_TOKEN \
          --secret $SHINY_SECRET \
          --title $SHINY_APP_NAME \
        if: env.SHINY_APP_ID == ''